apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- departement-deployment.yaml
- organization-deployment.yaml
- employee-deployment.yaml
namespace: argocd-sample-app
images:
- name: organization-image
  newName: harbor.tanzu.be/library/iso-organization-service
  newTag: b14.20210923.134754

- name: department-image
  newName: harbor.tanzu.be/library/iso-department-service
  newTag: b14.20210923.134754

- name: employee-image
  newName: harbor.tanzu.be/library/iso-employee-service
  newTag: b14.20210923.134754
  